### ISSUE TITLE
Handling authorization and authentication

### ISSUE THREAD

**Issue by Yaty** [strongloop/loopback4-example-microservices#97]
Hello LB team :)

It would be really nice to add how to handle authorization and authentication properly in this repository for LB4 with a microservices architecture.

I currently use LB3 for several microservices with the facade pattern and I encountered some pain-points about this. Maybe LB4 comes with a clean solution ?

Regards,

**Comment by dhmlau** [comment]
@Yaty, thanks for your interest in LB4.  Our goal in LB4 is to allow pluggable authentication and authorization strategies so that there is a cleaner separation of concern. Please see more details in one of our spike: https://github.com/strongloop/loopback-next/issues/1462, and continue the discussion there.  Thanks!

**Comment by dhmlau** [comment]
With the above comment, I'd like to close this issue.  Thanks @Yaty.
